tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('goto/', views.goto_url, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from rango.views import MyRegistrationView

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.about, name='about'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/',
         MyRegistrationView.as_view(),
         name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


    class Mate:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)



    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)


    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)


    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://'+url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from rango.models import Category, UserProfile
from rango.models import Page
from rango.forms import CategoryForm, UserForm, UserProfileForm
from rango.forms import PageForm
from registration.backends.simple.views import RegistrationView


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visit', '1'))

    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.datetime.now()))
    last_visit_time = datetime.datetime.strptime(last_visit_cookie[:-7],
                                                 '%Y-%m-%d %H:%M:%S')

    if (datetime.datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context_dict)


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):
    print(request.method)
    print(request.user)
    visit_dict = {}
    visit_dict['visits'] = request.session['visits']
    response = render(request, 'rango/about.html', visit_dict)
    return response


"""
class AboutView(View):
    def get(self, request):
        context_dict = {}
        context_dict['visits'] = request.session['visits']
        return render(request,
                      'rango/about.html',
                      context_dict)
"""


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


"""
class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})
    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
        return  render(request, 'rango/add_category', {'form': form})
"""


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                    category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


"""
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                registered = True
            else:
                print(user_form.errors, profile_form.errors)
        else:
            user_form = UserForm()
            profile_form = UserProfileForm

    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})
"""


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


def goto_url(request):
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
        selected_page.views = selected_page.views + 1
        selected_page.save()
        return redirect(selected_page.url)
    return redirect(reverse('rango:index'))


@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            if 'website' in request.POST:
                user_profile.website = request.POST['website']
            if 'picture' in request.FILES:
                user_profile.picture = request.FILES['picture']
            user_profile.save()

            return redirect('index')
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


"""
@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')
        userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('profile')
        else:
            print(form.errors)

    return render(request, 'rango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'form': form})
"""


class ProfileView(View):
    def get_user_detail(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        userprofile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': userprofile.website,
                                'picture': userprofile.picture})
        return (user, userprofile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_detail(username)
        except TypeError:
            return redirect('rango:index')
        context_dict = {'userprofile': userprofile,
                        'selecteduser': user,
                        'form': form}
        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_detail(username)
        except TypeError:
            return redirect('rango:index')

        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'userprofile': userprofile,
                        'selecteduser': user,
                        'form': form}
        return render(request, 'rango/profile.html', context_dict)


class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request,
                      'rango/list_profiles.html',
                      {'userprofile_list': profiles})


class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']
        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
      About
{% endblock %}

{% block body_block %}
<h1>About Page</h1>
<strong>you have visit {{visits}} times.</strong>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
<button class="btn btn-primary" id="about-btn">
      Click me - I'm using JQuery!
</button>
<p>This is some text for the JQuery example.</p>
<div id="msg">hello! I'm a further example for JQuery testing.</div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
   Add Category
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="category_form" method="post"
              action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{field.errors}}
            {{field.help_text}}<br/>
            {{field}}<br/>
            <div class="p-2"></div>
        {% endfor %}
        <br/>
        <button class="btn btn-primary" type="submit" name="submit">
            Add Category
        </button>
        <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_category_old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Category
{% endblock %}

{% block body_block %}
<h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category"/>
    </form>
</div>

{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}


{% block title_block %}
   Add Page
{% endblock %}

{% block body_block %}
{% if category %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add Page to{{category.name}}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post"
              action="{% url 'rango:add_page' category.slug">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{field.errors}}
            {{field.help_text}}<br/>
            {{field}}<br/>
            <div class="p-2"></div>
        {% endfor %}
        <br/>
            <button class="btn btn-primary" type="submit" name="submit">
             Add Page
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% else %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page</h1>
    </div>
</div>
<div>
    The specified category does not exist.
</div>
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/add_page_old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Page
{% endblock %}

{% block body_block %}
{% if category %}
<h1>Add a New Page to {{category.name}}</h1>
<div>
    <form id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="add Page"/>
    </form>
    {% else %}
    The specified category does not exist.
    {% endif %}

</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator"
          content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" >
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css"
          rel="stylesheet" >

      <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
    <a class="navbar-brand p-2" href="{ url 'rango:index' %}">Rango</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:restricted' %}">Restricted</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:add_category' %}">Add Category</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:profile'  user.username %}">Profile</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:list_profiles' %}">List Profiles</a>
    </li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'registration_register' %}">Register Here</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'auth_login' %}">Login</a></li>
    {% endif %}
    </ul>
    </div>
    </nav>
</header>

  <div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="w-75 ml-3">
          <input type="search"
                 id="search-input"
                 class="form-control ds-input"
                 placeholder="Search..."/>
      </div>
      <div class="sidebar-sticky" id="categories-listing">

      {% block sidebar_block %}
          {% get_category_list category %}
      {% endblock %}

      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    {% block body_block %}
    {% endblock %}
    <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy;2019 Tango With Django 2 &middot;<a href="#">Privacy</a>&middot;
        <a href="#">Terms</a></p>
    </footer>
    </main>
  </div>
  </div>

  <!-- Bootstrap core javascript -->
  <!-- Placed at the end of the document so the pages load faster -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          crossorigin="anonymous"></script>
  <script src="http://code.jquery.com/jquery-3.3.1.min.js"
          crossorigin="anonymous"></script>
  <script src="{% static 'js/rango-ajax.js' %}"
          crossorigin="anonymous"></script>
  <script>
      window.jQuery || document.write('<script src="http://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <script src="http://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="http://getbootstrap.com/docs/4.2/example/dashboard/dashboard.js"></script>

  <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
  </body>
</html>

tango_with_django_project/templates/rango/base_old.html
<!DOCTYPE html>

<!--
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
        How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
<div>
    {% block body_block %}
    {% endblock %}
</div>
<div>
    {% block sidebar_block %}
    {% get_category_list  category %}
    {% endblock %}
</div>
<hr/>
<div>
    <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
        <li><a href="{% url 'auth_password_change' %}?next={% url 'auth_password_change_done' %}">Password Change</a></li>
        {% else %}
        <li><a href="{% url 'auth_login' %}">Login</a></li>
        <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
        {% endif %}
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
</div>
</body>
</html>


<!doctype html>

{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" >
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>



    <link href="http://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" >


    <link href="http://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>
  <body>
  <header>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand p-2" href="{ url 'rango:index' %}">Rango</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auth">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:restricted' %}">Restricted</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'rango:add_category' %}">Add Category</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'registration_register' %}">Register Here</a></li>
    <li class="nav-item">
        <a class="nav-link"
           href="{% url 'auth_login' %}">Login</a></li>
    {% endif %}
    </ul>
    </div>
    </nav>
  </header>

  <div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
      {% block sidebar_block %}
          {% get_category_list category %}
      {% endblock %}
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    {% block body_block %}
    {% endblock %}
    <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy;2019 Tango With Django 2 &middot;<a href="#">Privacy</a>&middot;
        <a href="#">Terms</a></p>
    </footer>
    </main>
  </div>
  </div>




  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
  <script>
      window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <script src="http://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="http://getbootstrap.com/docs/4.2/example/dashboard/dashboard.js"></script></body>
</html>
-->

tango_with_django_project/templates/rango/categories.html
<!--
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li>
                    <strong><a href="{% url  'rango:show_category'  c.slug %}">{{c.name}}</a></strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url  'rango:show_category' c.slug %}">{{c.name}}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
</ul> -->

<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{c.name}}
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{c.name}}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock %}

{% block body_block %}
<h1>Hey!Happy for your login.Now you can see more.</h1>
<ul>
    <li><a href="{% url 'rango:index' %}">Index</a></li>
    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
    <li><a href="{% url 'auth_login' %}">Login</a></li>
    <li><a href="{% url 'rango:about' %}">About</a></li>
</ul>
{% endblock %}